In [1]:
import torch

In [68]:
a = torch.as_tensor([[1,0,0,0],[0,0,0,0],[1,0,0,1],[1,0,0,1]])

b = a[:,0] != 1

c = torch.as_tensor([False, True, True, False])

In [69]:
a[b.nonzero(), 2] = 7

In [42]:
b

tensor([0, 2, 3])

In [70]:
a

tensor([[1, 0, 0, 0],
        [0, 0, 7, 0],
        [3, 0, 7, 1],
        [6, 0, 7, 1]])

In [52]:
b.shape

torch.Size([4])

In [53]:
c.shape

AttributeError: 'list' object has no attribute 'shape'

In [63]:
b.nonzero()

tensor([[1],
        [2],
        [3]])

In [18]:
a = torch.rand(10) > 0.5

In [20]:
torch.where(a, 0,1)

tensor([1, 0, 1, 0, 0, 0, 0, 0, 0, 1])

In [9]:
b = torch.ones(10)

In [10]:
b

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [11]:
a

tensor([False, False, False,  True, False, False,  True, False,  True, False])

In [13]:
b[a] = b[a] *2

In [14]:
b

tensor([1., 1., 1., 2., 1., 1., 2., 1., 2., 1.])

In [15]:
a = torch.ones((4,4))

In [16]:
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [1]:
import torch

In [6]:
a = torch.ones(4, 5)

In [7]:
b = torch.rand(4, 5) * 2

In [12]:
b > 1

tensor([[ True,  True, False, False,  True],
        [False, False,  True, False, False],
        [False, False,  True, False,  True],
        [ True,  True,  True, False, False]])

In [9]:
torch.max(a, b)

tensor([[1.2622, 1.3072, 1.0000, 1.0000, 1.2682],
        [1.0000, 1.0000, 1.0015, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.4579, 1.0000, 1.4758],
        [1.7955, 1.6921, 1.8927, 1.0000, 1.0000]])

In [13]:
base = torch.ones(5)

In [14]:
half = torch.as_tensor([1,0,0,1,1])

In [15]:
mask = half == 0

In [16]:
mask

tensor([False,  True,  True, False, False])

In [17]:
reconstruction = torch.as_tensor([0.5, 0.5, 0.5, 0.5, 0.5])

In [23]:
adjusted_recon = reconstruction * mask.float()

In [24]:
prediction = half + adjusted_recon

In [25]:
loss = #diff of prediction and base

tensor([1.0000, 0.5000, 0.5000, 1.0000, 1.0000])